### PR TITLE
Feature/bug identification

### LINKED ISSUE #17: button to gather screen context
- url
- screenshot
- stagehand observe
- logs
- activity tracking?

That we can send to the model to help it gather context on where to make the code change

R+D: how to run stagehand or playwright directly on an iframe?

Or would we need to feed it some playwright steps first, to get to your spot on the page?

@thehimmat

### PR DESCRIPTION
**Pull request by thehimmat**
Resolves #17

This PR implements DOM debugging functionality for the task chat interface, allowing developers to click on elements in the browser preview to identify source code locations and attach debug information to chat messages.

## Key Features

- **DOM Element Inspection**: Click or drag to select elements in browser previews
- **Source Code Extraction**: Uses Babel + React DevTools to extract file names and line numbers
- **Debug Attachment Workflow**: Preview debug info before sending, with option to add context or cancel
- **Dual Development Modes**: 
  - `npm run dev` - Fast Turbopack development (debug features hidden)
  - `npm run dev:debug` - DOM debugging enabled with Babel (slower but full debugging)

## Implementation

- Component-based architecture (ChatArea, ChatInput, ArtifactsPanel)
- Conditional debug button visibility based on build mode
- Pending attachment system for user review before sending
- Comprehensive mock response system for meaningful debug feedback
- Automatic Babel configuration toggling between dev modes

## Testing

Feature has been thoroughly tested across the development workflow with both fast development and debugging modes working as intended.

### CODE REVIEW

**Comment by thehimmat** [comment]
## Merge Resolution Summary

Resolved complex merge conflicts with master branch (200+ files changed).

**Post-merge fixes:**
- Fixed duplicate messages by removing optimistic message creation
- Restored debug attachment preview workflow (was sending immediately)

**Preserved architecture:**
- Component refactor maintained (ChatArea/ChatInput/TaskStartInput)
- Babel debugging setup with dev/debug mode toggle intact
- All DOM debugging functionality working

**Current state:**
- All master updates integrated
- DOM debugging fully functional with new architecture
- Both dev workflows available (npm run dev vs npm run dev:debug)
- Ready for testing

Technical details in .projects/dom-debugging-feature.md

File: src/app/api/chat/message/route.ts [hunk 1]
```diff
@@ -321,15 +315,30 @@ export async function POST(request: NextRequest) {
...
-      ) as ContextTag[],
+      contextTags: parseContextTags(chatMessage.contextTags),
       artifacts: chatMessage.artifacts.map((artifact) => ({
         ...artifact,
         content: artifact.content as unknown,
       })) as Artifact[],
     };
 
+    // Broadcast the user message via Pusher to all connected clients for this task
+    if (taskId) {
```
Comment (Evanfeenstra) [inline src/app/api/chat/message/route.ts:326]: why push to pusher here?

File: src/app/api/debug-element/route.ts [hunk 2]
```diff
@@ -0,0 +1,99 @@
+import { NextRequest, NextResponse } from "next/server";
```
Comment (Evanfeenstra) [inline src/app/api/debug-element/route.ts:1]: what is this new route for?

File: src/app/api/proxy-preview/route.ts [hunk 3]
```diff
@@ -0,0 +1,55 @@
+import { NextResponse } from "next/server";
```
Comment (Evanfeenstra) [inline src/app/api/proxy-preview/route.ts:1]: what does this proxy preview route do?
